// GENERATED by tools/gen-content.mjs from tools/economy-model.mjs (+ shared/content/authored.js): do not edit.
// Barn upgrades (GDD §3.6): capacity after the upgrade; cost in coins plus Planks and Wooden Crates.
// Re-run `node tools/gen-content.mjs` after changing either; test/content.gen.test.js fails while stale.

export const BARN_UPGRADES = [
  { n: 1, m: 'M1a', unlock: 6, capacity: 320, cost: 3600, planks: 2, crates: 0 },
  { n: 2, m: 'M1a', unlock: 9, capacity: 440, cost: 8300, planks: 3, crates: 0 },
  { n: 3, m: 'M1a', unlock: 12, capacity: 560, cost: 16_000, planks: 4, crates: 1 },
  { n: 4, m: 'M1b', unlock: 15, capacity: 680, cost: 32_000, planks: 5, crates: 1 },
  { n: 5, m: 'M1b', unlock: 18, capacity: 800, cost: 50_000, planks: 6, crates: 1 },
  { n: 6, m: 'M1b', unlock: 21, capacity: 920, cost: 78_000, planks: 7, crates: 1 },
  { n: 7, m: 'M1b', unlock: 24, capacity: 1040, cost: 120_000, planks: 8, crates: 2 },
  { n: 8, m: 'M2', unlock: 27, capacity: 1160, cost: 160_000, planks: 9, crates: 2 },
  { n: 9, m: 'M2', unlock: 30, capacity: 1280, cost: 200_000, planks: 10, crates: 2 },
  { n: 10, m: 'M2', unlock: 33, capacity: 1400, cost: 260_000, planks: 11, crates: 2 },
];
