// GENERATED by tools/gen-content.mjs from tools/economy-model.mjs (+ shared/content/authored.js): do not edit.
// Feed (GDD §3.3). Inputs are ingredient CLASSES (cheapest live member first); feed is upkeep: never sold or ordered.
// Re-run `node tools/gen-content.mjs` after changing either; test/content.gen.test.js fails while stale.
import { min, h } from './units.js';

export const FEEDS = [
  { id: 'chicken_feed', name: 'Chicken Feed', m: 'M1a', building: 'feed_mill', unlock: 1, ms: min(5), out: 6,
    classes: [{ cls: 'grain', qty: 3 }], sell: 2, xp: 1, storePrice: 5 },
  { id: 'livestock_feed', name: 'Livestock Feed', m: 'M1a', building: 'feed_mill', unlock: 7, ms: min(10), out: 6,
    classes: [{ cls: 'grain', qty: 2 }, { cls: 'root', qty: 1 }], sell: 3, xp: 1, storePrice: 8 },
  { id: 'rabbit_greens', name: 'Rabbit Greens', m: 'M1b', building: 'feed_mill', unlock: 14, ms: min(10), out: 6,
    classes: [{ cls: 'root', qty: 2 }, { cls: 'veg', qty: 1 }], sell: 4, xp: 2, storePrice: 10 },
  { id: 'pig_slop', name: 'Pig Slop', m: 'M1b', building: 'feed_mill', unlock: 17, ms: min(10), out: 6,
    classes: [{ cls: 'produce', qty: 2 }], sell: 3, xp: 2, storePrice: 8 },
];
