// GENERATED by tools/gen-content.mjs from tools/economy-model.mjs (+ shared/content/authored.js): do not edit.
// Animal homes (GDD §3.4). capacity grows by upgradeStep per upgrade (upgradeCost each) up to capacityMax; count =
// how many of this home the farm may own at a level.
// Re-run `node tools/gen-content.mjs` after changing either; test/content.gen.test.js fails while stale.

export const HOMES = [
  { id: 'coop', name: 'Chicken Coop', m: 'M1a', kind: 'home', layer: 'object', size: [3, 3], unlock: 1, shop: true,
    cost: 0, species: ['chicken'], capacity: 6, capacityMax: 12, upgradeStep: 2, upgradeCost: 440,
    count: { base: 1, from: 1, every: 0, max: 1 }, growthBp: 0, model: 'homes/coop' },
  { id: 'cow_barn', name: 'Cow Barn', m: 'M1a', kind: 'home', layer: 'object', size: [4, 3], unlock: 7, shop: true,
    cost: 5300, species: ['cow'], capacity: 4, capacityMax: 8, upgradeStep: 2, upgradeCost: 3000,
    count: { base: 1, from: 7, every: 0, max: 1 }, growthBp: 0, model: 'homes/cow_barn' },
  { id: 'pasture', name: 'Sheep Pasture', m: 'M1a', kind: 'home', layer: 'object', size: [4, 4], unlock: 12,
    shop: true, cost: 14_000, species: ['sheep'], capacity: 4, capacityMax: 8, upgradeStep: 2, upgradeCost: 8000,
    count: { base: 1, from: 12, every: 0, max: 1 }, growthBp: 0, model: 'homes/pasture' },
  { id: 'beehive', name: 'Beehive', m: 'M1b', kind: 'home', layer: 'object', size: [1, 1], unlock: 13, shop: true,
    cost: 3400, species: ['bee'], capacity: 1, capacityMax: 1, upgradeStep: 0, upgradeCost: null,
    count: { base: 2, from: 13, every: 3, max: 8 }, growthBp: 1000, model: 'homes/beehive' },
  { id: 'hutch', name: 'Rabbit Hutch', m: 'M1b', kind: 'home', layer: 'object', size: [3, 2], unlock: 14, shop: true,
    cost: 20_000, species: ['rabbit'], capacity: 4, capacityMax: 8, upgradeStep: 2, upgradeCost: 11_000,
    count: { base: 1, from: 14, every: 0, max: 1 }, growthBp: 0, model: 'homes/hutch' },
  { id: 'pig_pen', name: 'Pig Pen', m: 'M1b', kind: 'home', layer: 'object', size: [4, 3], unlock: 17, shop: true,
    cost: 31_000, species: ['pig'], capacity: 4, capacityMax: 8, upgradeStep: 2, upgradeCost: 18_000,
    count: { base: 1, from: 17, every: 0, max: 1 }, growthBp: 0, model: 'homes/pig_pen' },
  { id: 'duck_pond', name: 'Duck Pond', m: 'M1b', kind: 'home', layer: 'object', size: [4, 4], unlock: 19, shop: true,
    cost: 39_000, species: ['duck'], capacity: 4, capacityMax: 8, upgradeStep: 2, upgradeCost: 22_000,
    count: { base: 1, from: 19, every: 0, max: 1 }, growthBp: 0, model: 'homes/duck_pond' },
  { id: 'goat_yard', name: 'Goat Yard', m: 'M1b', kind: 'home', layer: 'object', size: [4, 4], unlock: 22, shop: true,
    cost: 49_000, species: ['goat'], capacity: 4, capacityMax: 8, upgradeStep: 2, upgradeCost: 28_000,
    count: { base: 1, from: 22, every: 0, max: 1 }, growthBp: 0, model: 'homes/goat_yard' },
  { id: 'stable', name: 'Stable', m: 'M1b', kind: 'home', layer: 'object', size: [4, 3], unlock: 25, shop: true,
    cost: 59_000, species: ['horse'], capacity: 2, capacityMax: 4, upgradeStep: 2, upgradeCost: 34_000,
    count: { base: 1, from: 25, every: 0, max: 1 }, growthBp: 0, model: 'homes/stable' },
  { id: 'paddock', name: 'Alpaca Paddock', m: 'M2', kind: 'home', layer: 'object', size: [4, 4], unlock: 33,
    shop: true, cost: 88_000, species: ['alpaca'], capacity: 4, capacityMax: 8, upgradeStep: 2, upgradeCost: 50_000,
    count: { base: 1, from: 33, every: 0, max: 1 }, growthBp: 0, model: 'homes/paddock' },
];
