// GENERATED by tools/gen-content.mjs from tools/economy-model.mjs (+ shared/content/authored.js): do not edit.
// The model constants (GDD §4.3, §4.4, §4.6): what every price above was derived from. Read by tests (R1) and the
// report; the rules never use them.
// Re-run `node tools/gen-content.mjs` after changing either; test/content.gen.test.js fails while stale.

export const MODEL = {
  C: {
    CROP_R: 4.33, SHORT_EXP: 1, LONG_EXP: 0.45, CROP_LVL: 0.015, SEED_SHARE: 0.4, TREE_MULT: 1.6, TREE_GROWTH: 1.45,
    FEED_K: 4, ANIMAL_K: 18, CRAFT_K: 12, CRAFT_EXP: 0.8, CRAFT_LVL: 0.015, MIN_ADD: 0.15, XP_DIV: 8, ORDER_MULT: 1.5,
    STORE_MULT: 2.5
  },
  kAnchors: [
    [1, 1], [4, 1], [7, 1.05], [12, 1.3], [17, 1.85], [22, 2.44], [27, 2.75], [32, 2.98], [37, 3.18], [40, 3.26]
  ],
  xAnchors: [
    [1, 1.75], [4, 1.75], [7, 1.52], [8, 1.714], [9, 1.793], [10, 1.728], [11, 1.6875], [12, 1.85], [14, 1.922],
    [15, 3.429], [16, 3.158], [17, 2.876], [18, 2.706], [19, 2.521], [20, 2.067], [21, 1.723], [22, 1.981],
    [23, 1.676], [24, 1.365], [25, 2.09], [26, 1.87], [27, 1.67], [29, 1.6], [32, 1.5], [35, 1.37], [39, 1.2],
    [40, 1.2]
  ],
  targetMin: [
    3, 6, 12, 24, 24, 26, 28, 28, 29, 30, 40, 45, 50, 55, 60, 70, 75, 85, 90, 120, 150, 180, 210, 240, 270, 300, 330,
    360, 390, 420, 440, 460, 480, 500, 520, 540, 560, 580, 600, 620
  ],
  expLevels: [5, 7, 9, 11, 13, 15, 17, 19, 21, 24, 27, 30, 33, 36, 39],
  secondCopies: { mill: 16, dairy: 18, feed_mill: 31, pie_oven: 33 }
};
