#!/usr/bin/env node
// Writes docs/balance/content-report.md (and docs/balance/farm-layout.svg): every content family as a table, the
// per-level unlock list with milestones, the GDD §4.9 checks as run by the test suites, the starter farm map and the
// simulator's acceptance summary — so a human can audit the content at a glance.
//
//   node tools/content-report.mjs            full report (runs `node tools/econ-sim.mjs --checks --md`, ~20 s)
//   node tools/content-report.mjs --no-sim   skip the simulator (keeps the previous summary out of the report)
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  CONTENT, CONTENT_HASH, MILESTONE, CONFIG, ORDERS, COOP, GROWTH, FAIR, BARGE, TOWNSFOLK, TOWN_PROJECT_RULES,
  FARM_BEAUTY, MASTERWORK, COLLECTION_RULES, ALMANAC, isLive, live, validateContent, defOf, expansionObjects, plotCapOf,
  eHours, itemOf, levelRow, SEASONAL_TRACK, LEGACY, FESTIVAL_PAVILION, FISHING, DUEL, RESTED, INTERIOR, GRANDMA_VISIT,
  BREEDING,
} from '../shared/content/index.js';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = path.join(ROOT, 'docs', 'balance');
const SIM = !process.argv.includes('--no-sim');

const fmt = (n) => (typeof n === 'number' ? n.toLocaleString('en-US') : String(n ?? ''));
const dur = (ms) => {
  const m = ms / 60_000;
  if (m < 60) return `${m} min`;
  const h = Math.floor(m / 60);
  return m % 60 ? `${h} h ${m % 60} min` : `${h} h`;
};
const table = (head, rows) => [`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`,
  ...rows.map((r) => `| ${r.map((c) => (typeof c === 'number' ? fmt(c) : String(c ?? ''))).join(' | ')} |`)].join('\n');
const tick = (d) => (isLive(d) ? `**${d.m}**` : d.m);
const all = (fam) => [...CONTENT[fam].values()];
const inputs = (o) => Object.entries(o).map(([i, q]) => `${q} ${i}`).join(' + ');

const out = [];
const p = (s = '') => out.push(s);

p('# Harvest Hollow: content report');
p();
p(`Generated by \`node tools/content-report.mjs\` from \`shared/content/\` (CONTENT_HASH \`${CONTENT_HASH}\`,`
  + ` build milestone **${MILESTONE}**). Milestones in **bold** are live in this build; the rest exist as data and`
  + ' are unreachable in play'
  + ' (every action argument is validated against live content only).');
p();

// ---- summary -----------------------------------------------------------------------------------------------
p('## Summary');
p();
const fams = ['crops', 'trees', 'feeds', 'animals', 'homes', 'buildings', 'recipes', 'items', 'decor', 'expansions',
  'quests', 'ribbons', 'npcs', 'tools', 'features', 'collections', 'restoration', 'townProjects', 'decorSets',
  'festivals'];
p(table(['Family', 'All', `Live in ${MILESTONE}`], fams.map((f) => [f, CONTENT[f].size, live(f).length])));
p();
const problems = validateContent();
p(`validateContent(): **${problems.length ? `${problems.length} PROBLEMS` : 'no problems'}**.`);
for (const e of problems) p(`- ${e}`);
p();

// ---- §4.9 checks as run by the suites -----------------------------------------------------------------------
p('## GDD §4.9 checks (the content test suites)');
p();
const suites = ['test/economy.test.js', 'test/content.test.js', 'test/content.milestones.test.js',
  'test/content.m1b.test.js', 'test/content.layout.test.js', 'test/balance.test.js', 'test/content.gen.test.js'];
const tap = spawnSync(process.execPath, ['--test', '--test-reporter=tap', ...suites], { cwd: ROOT, encoding: 'utf8',
  maxBuffer: 1 << 26 });
const results = [...tap.stdout.matchAll(/^(not ok|ok) \d+ - (.+)$/gm)].map(([, st, name]) => [st === 'ok' ? 'pass'
  : '**FAIL**', name]);
p(table(['Result', 'Check'], results));
p();

// ---- unlocks per level -------------------------------------------------------------------------------------
p('## What unlocks at each level');
p();
const unlockFams = [['crops', 'crop'], ['trees', 'tree'], ['animals', 'animal'], ['homes', 'home'], ['buildings',
  'building'],
  ['recipes', 'recipe'], ['feeds', 'feed'], ['decor', 'decor'], ['tools', 'tool'], ['expansions',
    'land'], ['features', 'system']];
const rows = [];
for (let L = 1; L <= 40; L++) {
  const parts = [];
  for (const [fam, label] of unlockFams) {
    for (const d of all(fam)) {
      if (d.unlock !== L || d.shop === false || d.k === 0) continue;
      const name = isLive(d) ? `**${d.name}**` : d.name;
      parts.push(`${label} ${name}`);
    }
  }
  for (const b of CONTENT.barn) if (b.unlock === L) parts.push(isLive(b) ? `**barn upgrade ${b.n}**`
    : `barn upgrade ${b.n}`);
  const row = CONTENT.levels[L - 1];
  rows.push([L, row.m ?? (L <= 12 ? 'M1a' : L <= 25 ? 'M1b' : 'M2'), fmt(row.xp), fmt(row.xpToNext), fmt(row.E),
    row.coins,
    row.acorns, `${row.plotCap} (+6/exp.)`, parts.join('; ')]);
}
p(table(['Lvl', 'M', 'XP at', 'XP to next', 'E/h', 'Coins', 'Acorns', 'Plot cap', 'Unlocks (bold = live)'], rows));
p();

// ---- families ------------------------------------------------------------------------------------------------
p('## Crops');
p();
p(table(['Id', 'Crop', 'M', 'Lvl', 'Grow', 'Seed', 'Yield', 'Sell', 'Net/plot', 'XP', 'Season', 'Water', 'Fresh',
  'Mastery'],
  all('crops').map((c) => [`\`${c.id}\``, c.name, tick(c), c.unlock, dur(c.growMs), c.seed, c.yield, c.sell,
    c.sell * c.yield - c.seed, c.xp, c.season, c.waterable ? 'yes' : '—', dur(c.freshMs), c.mastery.join(' / ')])));
p();
p('## Trees');
p();
p(table(['Id', 'Tree', 'M', 'Lvl', 'Cost', 'Cycle', 'Yield', 'Product', 'XP', 'Tool', 'Bee forage'],
  all('trees').map((t) => [`\`${t.id}\``, t.name, tick(t), t.unlock, t.cost, dur(t.cycleMs), t.yield,
    `\`${t.product}\``,
    t.xp, t.tool, t.flowering ? 'yes' : '—'])));
p();
p('## Animals and homes');
p();
p(table(['Id', 'Animal', 'M', 'Lvl', 'Home', 'Baby', 'Adult', 'Grows', 'Eats', 'Cycle', 'Product', 'XP',
  'Blue ribbon after'],
  all('animals').map((a) => [`\`${a.id}\``, a.name, tick(a), a.unlock, a.homes.join(', '), a.baby ?? 'with hive',
    a.adult ?? '—',
    a.babyMs ? dur(a.babyMs) : '—', a.feed ? `${a.feedQty} ${a.feed}`
      : 'forage', dur(a.cycleMs), `${a.out} ${a.product}`,
    a.xp, a.prizedAt])));
p();
p(table(['Id', 'Home', 'M', 'Lvl', 'Size', 'Cost', 'Capacity', 'Upgrade (+step)'],
  all('homes').map((h) => [`\`${h.id}\``, h.name, tick(h), h.unlock, h.size.join('×'), h.cost,
    `${h.capacity}→${h.capacityMax}`,
    h.upgradeCost ? `${fmt(h.upgradeCost)} (+${h.upgradeStep})` : '—'])));
p();
p('## Buildings and recipes');
p();
p(table(['Id', 'Building', 'M', 'Lvl', 'Size', 'Cost', 'Slots', 'Slot costs', 'Second copy'],
  all('buildings').map((b) => [`\`${b.id}\``, b.name, tick(b), b.unlock, b.size.join('×'), b.cost,
    `${b.slots[0]}→${b.slots[1]}`,
    b.slotCosts.map(fmt).join(' / '), b.secondCopy ? `L${b.secondCopy.at}, ${fmt(b.secondCopy.cost)}` : '—'])));
p();
for (const b of all('buildings')) {
  const rs = [...all('recipes'), ...all('feeds')].filter((r) => r.building === b.id).sort((x,
    y) => x.unlock - y.unlock || x.ms - y.ms);
  if (!rs.length) continue;
  p(`### ${b.name} (\`${b.id}\`)`);
  p();
  p(table(['Id', 'Recipe', 'M', 'Lvl', 'Inputs', 'Time', 'Out', 'Sell/unit', 'XP', 'Tier'],
    rs.map((r) => [`\`${r.id}\``, r.name, tick(r), r.unlock, r.inputs ? inputs(r.inputs)
      : r.classes.map((c) => `${c.qty} ${c.cls}`).join(' + '),
      r.duet ? `${dur(r.ms)} duet / ${dur(r.ms * 2)} solo` : dur(r.ms), r.out, r.sell, r.duet
        ? `${r.xp} (${r.duetXp} together)` : r.xp,
      r.tier ?? 'feed'])));
  p();
}
p('## Items');
p();
p(table(['Id', 'Item', 'M', 'Kind', 'Lvl', 'Sell', 'Sellable', 'Orderable', 'Keep', 'Store price', 'Source'],
  all('items').map((i) => [`\`${i.id}\``, i.name, tick(i), i.tier ? `${i.kind} ${i.tier}` : i.kind, i.unlock, i.sell,
    i.sellable ? 'yes' : 'no', i.orderable ? 'yes' : 'no', i.keepDefault
      || '', i.storePrice ?? '', `\`${i.source}\``])));
p();
p('## Decor');
p();
p(table(['Id', 'Decor', 'M', 'Tier', 'Lvl', 'Price', 'Beauty', 'Size', 'Effect'],
  all('decor').map((d) => [`\`${d.id}\``, d.name, tick(d), d.tier, d.unlock, d.acorns ? `${d.acorns} Acorns`
    : d.cost || 'free',
    d.beauty10 / 10, d.size.join('×'), d.text || JSON.stringify(d.effect).replace(/[{}"]/g, '') || '—'])));
p();
p('## Land, Barn and plots');
p();
p(table(['#', 'Id', 'Expansion', 'M', 'Lvl', 'Coins', 'Planks', 'Crates', 'Rects', 'Proof', 'Arrives with'],
  all('expansions').map((e) => [e.k, `\`${e.id}\``, e.name, tick(e), e.unlock, e.cost, e.planks, e.crates,
    e.rects.map((r) => `[${r.join(',')}]`).join(' '),
    e.proof.map((t) => `${t.verb} ${t.qty} ${[].concat(t.ref).join('/')}`).join('; '),
    expansionObjects(e.id).filter((o) => !o.origin).map((o) => o.def).join(', ') || (e.k ? '15 debris' : '')])));
p();
p(table(['Upgrade', 'M', 'From lvl', 'Capacity', 'Coins', 'Planks', 'Crates'],
  [['Start', '**M1a**', 1, 200, 0, 0, 0], ...CONTENT.barn.map((b) => [b.n, tick(b), b.unlock, b.capacity, b.cost,
    b.planks, b.crates])]));
p();
const plot = CONTENT.plots.get('plot');
p(`Plots: the first ${plot.free} are free; plot cap = ${plotCapOf(1, 0)} at L1 + 1.5 per level + 6 per expansion `
  + `(L12 with 4 expansions: ${plotCapOf(12, 4)}). Prices: `
  + `${plot.prices.slice(0, 8).map(([n, c]) => `#${n}+ ${c}`).join(', ')} … `
  + `#${plot.prices.at(-1)[0]}+ ${fmt(plot.prices.at(-1)[1])}.`);
p();
p('## Quests (letters in `shared/content/story.js`)');
p();
p(table(['#', 'Giver', 'M', 'Lvl', 'Quest', 'Tasks', 'Coins', 'XP', 'Extra'],
  all('quests').map((q) => [q.id.toUpperCase(), q.giver, tick(q), q.level, q.title,
    q.tasks.map((t) => `${t.verb} ${t.qty} ${t.ref}`).join('; '), q.coins, q.xp,
    Object.entries(q.rewards).map(([k,
      v]) => `${k}: ${typeof v === 'object' ? JSON.stringify(v).replace(/["{}[\]]/g, '') : v}`).join('; ')])));
p();
p('## Ribbons');
p();
p(table(['#', 'Ribbon', 'M', 'Scope', 'Counter', 'Bronze / Silver / Gold', 'Gold title'],
  all('ribbons').map((r) => [r.n, r.name, tick(r), r.scope, `\`${r.stat}\` (${r.mode}${r.scale ? `,
    ×${r.scale}` : ''})`,
    r.tiers.map(fmt).join(' / '), r.title || (r.hidden ? 'hidden' : '')])));
p();
p('## Tools, systems, co-op numbers');
p();
p(table(['Id', 'Tool', 'M', 'Lvl', 'Cost', 'Brush'], all('tools').map((t) => [`\`${t.id}\``, t.name, tick(t),
  t.unlock, t.cost, t.brush.join('×')])));
p();
p(table(['Id', 'System', 'M', 'Lvl', 'Drip-feed card'], all('features').map((f) => [`\`${f.id}\``, f.name, tick(f),
  f.unlock, f.card ? `**${f.card.title}**: ${f.card.text}` : '—'])));
p();
p(`Orders: slots ${ORDERS.slots.map(([l, n]) => `${n} at L${l}`).join(', ')}; refill ${dur(ORDERS.refillMs)} `
  + `(the quick slot ${dur(ORDERS.quick.refillMs)}, goods ready within ${ORDERS.quick.readyMinutes} min); `
  + `pay 1.5 × V; golden every 6 h (+1 Acorn); first order ${JSON.stringify(ORDERS.first.items)}; `
  + `L5 budget ${fmt(eHours(5, ORDERS.budget[0][1]))}`
  + `–${fmt(eHours(5, ORDERS.budget[0][2]))} coins.`);
const pct = (bp) => `${bp / 100} %`;
p(`Co-op: partner tend −${pct(COOP.partnerTend.bp)} on top of watering −${pct(GROWTH.water.cropBp)} `
  + `(trees −${pct(GROWTH.water.treeBp)}); combo +${pct(COOP.combo.xpBonusBp)} XP within `
  + `${COOP.combo.windowMs / 1000} s and ${COOP.combo.radius} tiles; duet +${pct(COOP.duet.xpBonusBp)} XP, `
  + `solo ×${COOP.duet.soloTimeBp / 10_000} time; `
  + `Golden Hour −${pct(COOP.goldenHour.bp)} for ${dur(COOP.goldenHour.durationMs)}.`);
p();

// ---- M1b systems ------------------------------------------------------------------------------------------------
const bp = (n) => `${n / 100} %`;
const eh = (n) => `E x ${n / 10_000} h`;
p('## Weekly systems: County Fair, River Barge, townsfolk (GDD §5.6, §5.7, §5.3)');
p();
p(`County Fair (${tick(FAIR)}, L${FAIR.unlock}): week Monday 00:00 to Sunday ${FAIR.closeHour}:00; target W = `
  + `nice(${eh(FAIR.targetHoursBp)} / ${FAIR.pointValue}) points at Monday's level; a medal pays `
  + `${FAIR.payBp / 10_000} x its threshold value; at most ${FAIR.points.maxEntriesPerItem} entries of one item a `
  + `week; duet goods x${FAIR.points.duetMul}; NPC league ${FAIR.league.m} (L${FAIR.league.unlock}).`);
p();
p(table(['Medal', 'M', 'Share of W', 'Acorns', 'Extra'], FAIR.medals.map((m) => [m.name, m.m ?? FAIR.m,
  bp(m.atBp), m.acorns ?? 0, [m.trophy && 'trophy', m.banner && 'banner', m.goldenHourMs && '24 h Golden Hour',
    m.needsProject && `needs ${m.needsProject}`].filter(Boolean).join(', ')])));
p();
p(`River Barge (${tick(BARGE)}, L${BARGE.unlock}): docks day ${BARGE.dockDay} ${BARGE.dockHour}:00, casts off day `
  + `${BARGE.castOffDay} ${BARGE.castOffHour}:00; ${BARGE.rowsMin}-${BARGE.rowsMax} rows of ${BARGE.cratesPerRow} `
  + `crates (one row per ${dur(BARGE.playMsPerRow)} played last week); a crate = ${eh(BARGE.crateHoursBp)}, capped at `
  + `${dur(BARGE.producerCapMs)} of one producer, from goods made in the last ${BARGE.madeWithinMs / 86_400_000} days `
  + `(and at most one crate a week of a good never made yet, weight x${BARGE.neverMadeMul}); `
  + `pays ${BARGE.payBp / 10_000} x V (+${bp(BARGE.horseBp)} a horse, max +${bp(BARGE.horseMaxBp)}); a row pays `
  + `${eh(BARGE.row.coinsHoursBp)} (+${bp(BARGE.row.riverbankBp)} after Riverbank) + ${BARGE.row.acorns} Acorn + `
  + `1/${BARGE.row.chestShareDiv} of the Captain's chest (tier 1-${BARGE.chest.tiers}: 1 + t Acorns, `
  + `${BARGE.chest.compostPerTier}t Compost, a decor roll from tier ${BARGE.chest.decorFrom}).`);
p();
const fr = TOWNSFOLK.friendship;
p(`Townsfolk board (${tick(TOWNSFOLK)}, L${TOWNSFOLK.unlock}): ${TOWNSFOLK.postsPerWeek} requests a week of `
  + `${TOWNSFOLK.goods.join('-')} goods worth ${eh(TOWNSFOLK.valueHoursBp)}, paid ${TOWNSFOLK.payBp / 10_000} x V `
  + `(${bp(TOWNSFOLK.coinShareBp)} coins; a fresh board once a week when all are handed in). `
  + `Friendship up to ${fr.max}: golden order +${fr.goldenOrder}, request `
  + `+${fr.request}, chain quest +${fr.chainQuest}, one liked gift a day +${fr.giftPerDay}; a gift every `
  + `${fr.rewardEvery}:`);
p();
p(table(['Townsperson', 'From', 'Likes', ...[2, 4, 6, 8, 10].map((n) => `At ${n}`)],
  all('npcs').filter((n) => n.townsfolk).map((n) => [n.name, `L${n.from}`, n.likes.join(', '),
    ...(fr.rewards[n.id] ?? []).map((g) => (g.decor ? `decor ${g.decor}` : `${itemOf(g.card)?.name} card`))])));
p();
p('## Long-term systems: Restoration, Town Projects, Farm Beauty, decor sets, collections (GDD §5.5, §5.9)');
p();
const slotTxt = (sl) => (sl.item ? `${sl.qty} ${sl.item}` : sl.special ? `${sl.qty} ${sl.special}`
  : eh(sl.coinsHoursBp));
p(table(['#', 'Project', 'M', 'Lvl', 'Bundles (any N of M)', 'Reward'], all('restoration').map((r) => [r.n, r.name,
  tick(r), r.unlock, r.bundles.map((b) => `${b.name} ${b.need} of ${b.slots.length} (${b.slots.map(slotTxt)
    .join(', ')})`).join(' · '), r.text])));
p();
p(`Town Projects (L${TOWN_PROJECT_RULES.unlock}): one at a time; goods ${eh(TOWN_PROJECT_RULES.goodsHoursBp)} `
  + `(${TOWN_PROJECT_RULES.goods} goods made in the last 14 days and makeable now, each at most `
  + `${dur(TOWN_PROJECT_RULES.producerCapMs)} of the producers owned), coins E x (${TOWN_PROJECT_RULES.coinsHoursBaseBp
  / 10_000} + ${TOWN_PROJECT_RULES.coinsHoursStepBp / 10_000} (n - 1)) h; built ${dur(TOWN_PROJECT_RULES.buildMs)} `
  + `later; ${TOWN_PROJECT_RULES.acorns} Acorns, a souvenir and a Memory Book page.`);
p();
p(table(['#', 'Project', 'M', 'What it brings', 'Souvenir'], all('townProjects').map((t) => [t.n, t.name, tick(t),
  t.text, `\`${t.souvenir}\``])));
p();
p(`Farm Beauty (L${FARM_BEAUTY.unlock}): stars at ${FARM_BEAUTY.stars.join(' / ')}; copies `
  + `${FARM_BEAUTY.copyBp.map(bp).join(' / ')}; +${bp(FARM_BEAUTY.pathBp)} touching a path; sets +${bp(FARM_BEAUTY.setBp)};`
  + ` ${FARM_BEAUTY.building} per building, ${FARM_BEAUTY.tree} per tree; a star pays ${FARM_BEAUTY.starAcorns} Acorns `
  + `and +${bp(FARM_BEAUTY.orderCoinsBpPerStar)} order coins. Masterwork: ${MASTERWORK.priceMul.join(' x / ')} x `
  + `the price for ${MASTERWORK.beautyBp.map((b) => `${b / 10_000} x`).join(' / ')} beauty.`);
p();
p(table(['Set', 'M', 'Lvl', 'Pieces (within ' + all('decorSets')[0].radius + ' tiles)', 'Cosmetic'],
  all('decorSets').map((d) => [d.name, tick(d), d.unlock, d.pieces.map((id) => defOf(id).name).join(', '),
    d.cosmetic])));
p();
p(`Collections (L${COLLECTION_RULES.unlock}): ${bp(COLLECTION_RULES.dropBp)} per eligible action (x`
  + `${COLLECTION_RULES.goldMul} for Gold-mastered sources), pity after ${COLLECTION_RULES.pity}, duplicates `
  + `${COLLECTION_RULES.tradeIn} -> 1, a set pays ${COLLECTION_RULES.acorns} Acorns + its display piece + a perk.`);
p();
p(table(['Set', 'M', 'Found by', 'Items', 'Perk'], all('collections').map((c) => [c.name, tick(c), c.from.join(', '),
  c.items.map((x) => x.name).join(', '), c.perkText])));
p();
p(`First evening (RC-01): the Almanac from L${ALMANAC.unlock} (${ALMANAC.tasksPerPlayer} tasks each, the first `
  + `${ALMANAC.paidPerDay} a day pay ${eh(ALMANAC.coinsBp)}); the quick order refills every `
  + `${dur(ORDERS.quick.refillMs)}.`);
p();

// ---- M2 systems (wave 3) ---------------------------------------------------------------------------------------
p('## M2 systems: league, track, Legacy, fishing, duel, rested XP, the farmhouse (GDD §4.7, §5.6, §5.9, §6.2)');
p();
const rw = (r) => Object.entries(r).map(([k, v]) => (k === 'items' ? inputs(v) : k === 'coinsHoursBp' ? eh(v)
  : k === 'decor' ? (v === 'season' ? 'the season\'s planter' : defOf(v)?.name ?? v) : k === 'coat'
    ? 'the season\'s coat' : `${v} ${k}`)).join(' + ');
const lg = FAIR.league;
p(`NPC league (L${lg.unlock}, ${lg.m}): ${lg.names.join(' · ')}; NPC week = W x (${bp(lg.npcMinBp)} + `
  + `${bp(lg.npcSpreadBp)} x hash01); top ${lg.promote} up, last ${lg.demote} down; league x ${lg.acornsPerTier} Acorn a `
  + `week; the top league needs \`${lg.topNeedsProject}\`.`);
p();
p(table(['NPC farm', 'Farmer', 'Motto'], lg.npcs.map((n) => [n.name, n.farmer, n.motto])));
p();
p(`Seasonal Ribbon Track (L${SEASONAL_TRACK.unlock}): ${SEASONAL_TRACK.tiers} tiers of about `
  + `${SEASONAL_TRACK.tierHours} h of play; coins over the whole track `
  + `${eh(SEASONAL_TRACK.rewards.reduce((a, r) => a + (r.coinsHoursBp ?? 0), 0))}; season coats `
  + `${BREEDING.seasonCoats.map((c) => `${c.id} (${c.season})`).join(', ')}.`);
p();
p(table(['Tier', 'Reward'], SEASONAL_TRACK.rewards.map((r, i) => [i + 1, rw(r)])));
p();
p(`Legacy levels (from L${LEGACY.from}, in turn): ${LEGACY.pool.map(rw).join(' · ')}.`);
p();
p(`Festival Pavilion (after Town Project ${FESTIVAL_PAVILION.after}): `
  + `${FESTIVAL_PAVILION.tiers.map((t, i) => `${i + 1}. ${t.name}`).join(' · ')} (the last repeats).`);
p();
p(`Fishing Dock (L${FISHING.unlock} at Willow Pond, or the Fishing Dock decor from L${FISHING.spots.decorFrom}): one `
  + `${dur(FISHING.castMs).replace('0.3333333333333333 min', '20 s')} cast per player per ${dur(FISHING.cooldownMs)}; `
  + `never an economy item; each cast rolls the ${FISHING.collectionSet} set.`);
p();
p(table(['Fish', 'Size (cm)', 'Chance'], FISHING.fish.map((f) => [f.name, `${f.cm[0]}–${f.cm[1]}`, bp(f.weightBp)])));
p();
p(`Friendly Duel (L${DUEL.unlock}, opt-in): ${DUEL.kinds.map((k) => `${k.name} (${k.text})`).join(' · ')}; the winner `
  + `is "${DUEL.crown.title}" for ${dur(DUEL.crown.ms)}, both get ${DUEL.rewards.hearts} Hearts.`);
p();
p(`Rested XP (L${RESTED.unlock}): ${bp(RESTED.bp)} of a personal level's requirement per ${dur(RESTED.perMs)} away, `
  + `at most ${bp(RESTED.capBp)}; doubles personal XP until used; farm XP never.`);
p();
const shopF = all('furniture').filter((f) => f.shop);
const E34 = levelRow(34).E;
const byCat = {};
for (const f of shopF) byCat[f.cat] = (byCat[f.cat] ?? 0) + f.cost * f.max;
p(`The farmhouse interior (after \`${INTERIOR.needsProject}\`): a ${INTERIOR.grid.join(' x ')} room, wall slots `
  + `${INTERIOR.walls.back} + ${INTERIOR.walls.left}; ${shopF.length} catalog pieces, `
  + `${(shopF.reduce((a, f) => a + f.cost * f.max, 0) / E34).toFixed(2)} E(34)-hours for everything; Grandma stays `
  + `${dur(GRANDMA_VISIT.stayMs)} and leaves her portrait.`);
p();
p(table(['Category', 'Pieces', 'Coins (all copies)', 'E(34)-hours'], Object.entries(byCat).map(([cat, c]) => [cat,
  shopF.filter((f) => f.cat === cat).map((f) => f.name).join(', '), c, (c / E34).toFixed(2)])));
p();
p('Late-game coin sinks in hours of income at their level (the treasury check of Appendix E):');
p();
const sinks = [
  ...all('expansions').filter((e) => e.m === 'M2').map((e) => [e.name, e.unlock, e.cost]),
  ...all('buildings').filter((b) => b.m === 'M2').map((b) => [b.name, b.unlock, b.cost]),
  ...all('decor').filter((d) => d.tier === 'grand').map((d) => [d.name, d.unlock, d.cost]),
  ...[30, 35, 40].map((L) => [`Town Project #${L - 17} at L${L} (coins)`, L,
    eHours(L, TOWN_PROJECT_RULES.coinsHoursBaseBp + (L - 18) * TOWN_PROJECT_RULES.coinsHoursStepBp)]),
];
p(table(['Sink', 'Lvl', 'Coins', 'E-hours'], sinks.map(([n, L, c]) => [n, L, c, (c / levelRow(L).E).toFixed(2)])));
p();

// ---- the starter farm map -------------------------------------------------------------------------------------
p('## The starter farm (Homestead, tiles x 16–39, z 24–39)');
p();
const CH = { farmhouse: 'H', barn: 'B', well: 'W', mailbox: 'm', market_stand: 'M', order_board: 'O', picket_fence: 'f',
  dirt_path: '.', weed: 'w', rock: 'r', stump: 's', log: 'l', boulder: '@', plot: '#' };
const grid = {};
const stamp = (def, x, z) => {
  const d = defOf(def);
  for (let dz = 0; dz < d.size[1]; dz++) {
    for (let dx = 0; dx < d.size[0]; dx++) grid[`${x + dx},${z + dz}`] = CH[def] ?? '?';
  }
};
for (const o of CONFIG.START.objects.filter((x) => x.def === 'dirt_path')) stamp(o.def, o.x, o.z);
for (const [x, z] of CONFIG.START.plots) stamp('plot', x, z);
for (const o of CONFIG.START.objects.filter((x) => x.def !== 'dirt_path')) stamp(o.def, o.x, o.z);
const lines = ['     x 16      24      32    39'];
for (let z = 24; z < 40; z++) {
  let row = `z ${String(z).padStart(2)} `;
  for (let x = 16; x < 40; x++) row += grid[`${x},${z}`] ?? ' ';
  lines.push(row);
}
p('```');
p(lines.join('\n'));
p('```');
p('H farmhouse · B barn · W well · m mailbox · M Market Stand · O Order Board · # plot · f fence · . path · '
  + 'w weed · r rock · s stump · l log · @ boulder. Avatars spawn on the porch (20.5, 29.5) and (22, 29.5). '
  + '![farm layout](farm-layout.svg)');
p();

// ---- the simulator ---------------------------------------------------------------------------------------------
if (SIM) {
  p('## Simulator acceptance (`node tools/econ-sim.mjs --checks --md`)');
  p();
  const sim = spawnSync(process.execPath, [path.join(ROOT, 'tools', 'econ-sim.mjs'), '--checks', '--md'],
    { cwd: ROOT, encoding: 'utf8', maxBuffer: 1 << 26 });
  p(`Exit code **${sim.status}**${sim.status === 0 ? ' (every acceptance check passed)' : ' (FAILURES below)'}.`);
  p();
  const md = sim.stdout;
  const start = md.indexOf('#### Acceptance');
  p((start >= 0 ? md.slice(start) : md).trim().replace(/^#### /gm, '### '));
  p();
}

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(path.join(OUT_DIR, 'content-report.md'), `${out.join('\n')}\n`);

// ---- SVG map of the whole farm: parcels by expansion, the starter objects, every expansion's arrivals -----------
const S = 12;
const colors = { plot: '#8B5A2B', landmark: '#C0392B', decor: '#E9B44C', path: '#D9C08C', debris: '#7F8C8D',
  tree: '#2E8B57',
  home: '#9B59B6' };
const view = `${7 * S} ${7 * S} ${50 * S} ${50 * S}`;
const svg = [`<svg xmlns="http://www.w3.org/2000/svg" viewBox="${view}" width="${50 * S}" height="${50 * S}"`
  + ' font-family="sans-serif">',
  `<rect x="${7 * S}" y="${7 * S}" width="${50 * S}" height="${50 * S}" fill="#5E8F4A"/>`];
const hue = (k) => `hsl(${(k * 47) % 360} 45% ${k === 0 ? 62 : 52}%)`;
for (const e of all('expansions')) {
  for (const [x, z, w, d] of e.rects) {
    const label = e.k ? `${e.k} ${e.name} (L${e.unlock})` : 'Homestead';
    svg.push(`<rect x="${x * S}" y="${z * S}" width="${w * S}" height="${d * S}" fill="${hue(e.k)}" stroke="#2c3e2c"`
      + ' stroke-width="1.5" opacity="0.85"/>');
    svg.push(`<text x="${(x + 0.3) * S}" y="${(z + 1) * S}" font-size="10" fill="#1b2a1b">${label}</text>`);
  }
}
const rect = (x, z, w, d, fill) => svg.push(
  `<rect x="${x * S + 1}" y="${z * S + 1}" width="${w * S - 2}" height="${d * S - 2}" rx="2" fill="${fill}"/>`);
for (const o of CONFIG.START.objects) {
  const d = defOf(o.def);
  const kind = o.def === 'dirt_path' ? 'path' : d.kind === 'debris' ? 'debris' : d.kind === 'landmark' ? 'landmark'
    : 'decor';
  rect(o.x, o.z, d.size[0], d.size[1], colors[kind]);
}
for (const [x, z] of CONFIG.START.plots) rect(x, z, 1, 1, colors.plot);
for (const e of all('expansions')) {
  for (const o of expansionObjects(e.id)) {
    const d = defOf(o.def);
    rect(o.x, o.z, d.size[0], d.size[1], o.origin ? colors.debris : d.kind === 'tree' ? colors.tree
      : d.kind === 'home' ? colors.home : colors.decor);
  }
}
for (const sp of Object.values(CONFIG.START.spawn)) {
  svg.push(`<circle cx="${sp.x * S}" cy="${sp.z * S}" r="4" fill="#2BB3A3" stroke="#fff"/>`);
}
svg.push('</svg>');
fs.writeFileSync(path.join(OUT_DIR, 'farm-layout.svg'), `${svg.join('\n')}\n`);
console.log(JSON.stringify({ ok: problems.length === 0 && results.every(([r]) => r === 'pass'), checks: results.length,
  failed: results.filter(([r]) => r !== 'pass').map(([, n]) => n), files: ['docs/balance/content-report.md',
    'docs/balance/farm-layout.svg'] }));
